### PR TITLE
Nav

### PR DESCRIPTION
**Pull request by histtranger**

### CODE REVIEW

**Review by hldouglas — CHANGES_REQUESTED** [review]
In _layouts/default.html please remove css grid, modules, type, and main. weather.css is meant to link all four of them without having to put them in.
In css/main.css the .active class is empty. Please style or delete it.
In patterns/buttons.css all the hex colours should be written as their var colour from the root section in theme.css.
There is also a conflict between the _layout/default.html and css/main.css files.

**Comment by histtranger** [comment]
Made changes

**Review by hldouglas — DISMISSED** [review]
Changes were fixed, and is fine to merge.

**Review by hldouglas — APPROVED** [review]
Resolved issues of overlapping code

**Pull request merged**
